<a href="https://colab.research.google.com/github/Chaitra-B-V/CMPE-258-DeepLearning/blob/main/Assignments/2c-Tensor%20Operation/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

Broadcasting

Smaller tensors are stretched automatically inorder to fit larger tensors when running combined operations on them

For example, when we multiply or add a tensor with a scalar, the scalar is broadcast to the same shape as the other argument

In [2]:
x = tf.constant([4,5,6])
y = tf.constant(2)
z = tf.constant([3, 3, 3])

#Broadcasting happens here
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([12 15 18], shape=(3,), dtype=int32)


In [3]:
# Broadcasting with respect to matrix multiplication
x = tf.reshape(x,[3,1])
y = tf.range(2,5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

a = tf.constant([2,4,6,7])
b = tf.constant([1,2,3,4])
print(tf.add(a,b)) 

tf.Tensor(
[[4]
 [5]
 [6]], shape=(3, 1), dtype=int32) 

tf.Tensor([2 3 4], shape=(3,), dtype=int32) 

tf.Tensor(
[[ 8 12 16]
 [10 15 20]
 [12 18 24]], shape=(3, 3), dtype=int32)
tf.Tensor([ 3  6  9 11], shape=(4,), dtype=int32)


String tensors 

String tensors are used to represent data as strings in tensors

In [26]:
#scalar string
scalar_string_tensor = tf.constant("Back Propogation")
print(scalar_string_tensor)

tf.Tensor(b'Back Propogation', shape=(), dtype=string)


In [27]:
#vector of strings
tensor_of_strings = tf.constant(["Back Propogation",
                                 "Tensor String",
                                 "Neural networks"])

print(tensor_of_strings)

tf.Tensor([b'Back Propogation' b'Tensor String' b'Neural networks'], shape=(3,), dtype=string)


some string functions with tf.strings

In [6]:
#splitting scalar string based on space
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Deep' b'Learning'], shape=(2,), dtype=string)


In [7]:
#splitting vector of strings
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Deep', b'Learning'],
 [b'Machine', b'Learning'],
 [b'Neural', b'networks']]>


In [8]:
#converting string to number
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [9]:
#converting strings to bytes, then numbers
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


Sparse Tensors

Sparse tensors are used when data is sparse. Tensorflow stores sparse data efficiently

In [10]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

#converting sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


Ragged Tensors

Tensors with variable number of elements along some axis is called ragged tensors. 

In [11]:
#example of a ragged list(not regular)
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [12]:
#this wont work because the shape of the tensor is not normal or usual
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [13]:
#creating a ragged tensor
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [14]:
print(ragged_tensor.shape)

(4, None)


Named Tensor : Implementing this in Pytorch, as tensorflow does not use named dimensions for it's tensors

Pytorch

In [15]:
import torch

Named Tensor

Naming the dimensions of the tensor using named tensor, this will help when performing permutations and provides extra safety

In [16]:
torch.zeros(2, 3, names=('N', 'C'))

<ipython-input-16-eb74a8e0f1fd>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  torch.zeros(2, 3, names=('N', 'C'))


tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))

In [17]:
imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))
imgs.names

('N', 'C', 'H', 'W')

In [18]:
renamed_imgs = imgs.rename(H='height', W='width')
renamed_imgs.names

('N', 'C', 'height', 'width')

Broadcasting

Smaller tensors are stretched automatically inorder to fit larger tensors when running combined operations on them

For example, when we multiply or add a tensor with a scalar, the scalar is broadcast to the same shape as the other argument

In [19]:
x = torch.tensor([4,5,6])
y = torch.tensor(2)
z = torch.tensor([3, 3, 3])
 
#Broadcasting happens here
print(torch.mul(x, 2))
print(x * y)
print(x * z)

tensor([ 8, 10, 12])
tensor([ 8, 10, 12])
tensor([12, 15, 18])


In [20]:
# Broadcasting with respect to matrix multiplication
x = torch.reshape(x,[3,1])
y = torch.range(2,5)
print(x, "\n")
print(y, "\n")
print(torch.mul(x, y))

a = torch.tensor([2,4,6,7])
b = torch.tensor([1,2,3,4])
print(torch.add(a,b)) 

<ipython-input-20-9b7fc9d8080b>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  y = torch.range(2,5)


tensor([[4],
        [5],
        [6]]) 

tensor([2., 3., 4., 5.]) 

tensor([[ 8., 12., 16., 20.],
        [10., 15., 20., 25.],
        [12., 18., 24., 30.]])
tensor([ 3,  6,  9, 11])


String tensors 

String tensors are used to represent data as strings in tensors

using Tensorflow we can store string in tensors, but with pytorch, we can only use the following ways to store a string in tensor

In [21]:
string = "Deep Learning"
ascii_codes = [ord(c) for c in string]
print(torch.tensor(ascii_codes))

tensor([ 68, 101, 101, 112,  32,  76, 101,  97, 114, 110, 105, 110, 103])


In [22]:
scalar_tensor = torch.tensor(3)

string_value = "5"
numerical_value = int(string_value)

str_tensor = torch.tensor(numerical_value)
print(str_tensor)

tensor(5)


Sparse Tensors

Sparse tensors are used when data is sparse. Using Pytorch to store sparse data

In [23]:
import torch

indices = torch.tensor([[0, 1], [1, 2], [2, 0]])
values = torch.tensor([1, 2, 3])

sparse_tensor = torch.sparse_coo_tensor(indices.t(), values, size=(3, 3))

print(sparse_tensor)

print(sparse_tensor[1, 2])

tensor(indices=tensor([[0, 1, 2],
                       [1, 2, 0]]),
       values=tensor([1, 2, 3]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)
tensor(2)


Ragged Tensors - Nested Tensor in Pytorch

Tensors with variable number of elements along some axis is called ragged tensors. In pytorch we use nested tensor for ragged tensors.

In [24]:
a, b = torch.arange(3), torch.arange(5) + 3
nt = torch.nested.nested_tensor([a, b])
print("a: ", a)
print("b: ", b)
print("nested tensor: ", nt)

a:  tensor([0, 1, 2])
b:  tensor([3, 4, 5, 6, 7])
nested tensor:  nested_tensor([
  tensor([0, 1, 2]),
  tensor([3, 4, 5, 6, 7])
])


/usr/local/lib/python3.8/dist-packages/torch/nested/__init__.py:47: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:175.)
  nt = torch._nested_tensor_from_tensor_list(new_data, dtype, None, device, pin_memory)


In [25]:
nt.dim()

2